# Materials that are not flagged while walking through them. Types found here: http://goo.gl/JIs4zo
translucent-materials:
  - AIR
  - ACACIA_STAIRS
  - ANVIL
  - BEACON
  - BED_BLOCK
  - BIRCH_WOOD_STAIRS
  - BREWING_STAND
  - BRICK_STAIRS
  - CAULDRON
  - CHEST
  - COBBLE_WALL
  - COBBLESTONE_STAIRS
  - COCOA
  - DARK_OAK_STAIRS
  - DAYLIGHT_DETECTOR
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - DRAGON_EGG
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ENDER_PORTAL_FRAME
  - FENCE
  - FENCE_GATE
  - ENDER_PORTAL
  - FLOWER_POT
  - HOPPER
  - IRON_FENCE
  - JUNGLE_WOOD_STAIRS
  - NETHER_BRICK_STAIRS
  - NETHER_FENCE
  - PISTON_BASE
  - PISTON_EXTENSION
  - PISTON_MOVING_PIECE
  - PISTON_STICKY_BASE
  - QUARTZ_STAIRS
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - SANDSTONE_STAIRS
  - SKULL
  - SNOW
  - SMOOTH_STAIRS
  - SOUL_SAND
  - SPRUCE_WOOD_STAIRS
  - STEP
  - TRAP_DOOR
  - TRAPPED_CHEST
  - WATER_LILY
  - WOOD_STAIRS
  - WOOD_STEP
  - ACTIVATOR_RAIL
  - AIR
  - BROWN_MUSHROOM
  - CACTUS
  - CARPET
  - CARROT
  - CROPS
  - DEAD_BUSH
  - DETECTOR_RAIL
  - DOUBLE_PLANT
  - FIRE
  - GOLD_PLATE
  - IRON_DOOR_BLOCK
  - IRON_PLATE
  - LADDER
  - LAVA
  - LEVER
  - LONG_GRASS
  - MELON_STEM
  - NETHER_WARTS
  - PORTAL
  - POTATO
  - POWERED_RAIL
  - PUMPKIN_STEM
  - RAILS
  - RED_MUSHROOM
  - RED_ROSE
  - REDSTONE_TORCH_OFF
  - REDSTONE_TORCH_ON
  - REDSTONE_WIRE
  - SAPLING
  - SEEDS
  - SIGN_POST
  - STAINED_GLASS_PANE
  - STATIONARY_LAVA
  - STATIONARY_WATER
  - STONE_BUTTON
  - STONE_PLATE
  - SUGAR_CANE_BLOCK
  - THIN_GLASS
  - TORCH
  - TRIPWIRE
  - TRIPWIRE_HOOK
  - VINE
  - WALL_SIGN
  - WATER
  - WEB
  - WOOD_BUTTON
  - WOOD_PLATE
  - WOODEN_DOOR
  - YELLOW_FLOWER
  - LAVA
  - STATIONARY_LAVA
  - STATIONARY_WATER
  - WATER